/**
 * CommonEnums.ets
 * 简要描述：
 * 作者：橙子
 * 日期：2025/10/28
 */
export enum AppStorageMap {
  USER_INFO = 'userInfo',
  TOKEN = 'token',
  PRIVACY_POLICY_KEY='0'
}

export enum RouterMap {
  // 启动页
  LAUNCH_PAGE = 'LaunchPage',
  // 广告页
  LAUNCH_AD_PAGE = 'LaunchAdPage',
  // 入口页
  MAIN_ENTRY = 'MainEntry',
  // 隐私协议
  PRIVACY_POLICY_PAGE = 'PrivacyPolicyPage',
  // 首页
  HOME_PAGE = 'HomePage',
  // 课程页面
  COURSE_PAGE = 'CoursePage',
  // 学习页面
  STUDY_PAGE = 'StudyPage',
  // 个人主页
  PROFILE_PAGE = 'ProfilePage',
  // 登录页面
  LOGIN_PAGE = 'LoginPage',
  // 课程详情页面
  COURSE_DETAIL_PAGE = 'CourseDetailPage',
  // 搜索页面
  SEARCH_PAGE = 'SearchPage',
  // 消息页面
  MESSAGE_PAGE = 'MessagePage',
  // 消息详情页面
  MESSAGE_DETAIL_PAGE = 'MessageDetailPage',

  MAIN_PAGE='MainPage'
}